# Site settings
title: "Projektrealisierung<br>Webentwicklung"
description: "Entwickler // Java EE 7 & JSF // HTML5 & CSS3 mit SASS // Webserver // Konzeption // Open GL"
email: webapps@klausschlender.com

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :compressed
